### ISSUE TITLE
condition in FiniteDiffMatrix is boolean, but a list is expected.

### ISSUE THREAD

**Issue by charlesflorian** [thimmis/heat_equation#2]
I get the following error:

```
$ python problem_solver.py 
Traceback (most recent call last):
  File "problem_solver.py", line 178, in <module>
    tester(20,10)
  File "problem_solver.py", line 170, in __call__
    self.OM1, self.OM2, self.OM3, self.OM4 = self.dirichelt_neumann_iteration(self.heater, self.aircon, self.wall, cols, iters, open)
  File "problem_solver.py", line 43, in dirichelt_neumann_iteration
    livingroom = room_livingroom.LivingRoom(heater, aircon, walls, cols, open)
  File "/Users/simonrose/Documents/coding/python/heat_equation/room_livingroom.py", line 91, in __init__
    self.behaviour_matrix = matrix_creator.FiniteDiffMatrix(self.rows+2,self.cols+2).A
  File "/Users/simonrose/Documents/coding/python/heat_equation/matrix_creator.py", line 37, in __init__
    self.stamp = self.create_kron_stamp()
  File "/Users/simonrose/Documents/coding/python/heat_equation/matrix_creator.py", line 69, in create_kron_stamp
    if 'l' in self.condition:
TypeError: argument of type 'bool' is not iterable
```

This seems to be because FiniteDiffMatrix has its condition initialized as a boolean, but it seems to serve a different purpose in create_kron_stamp(). However, this condition isn't ever passed as an argument in any of the places that call it.

**Comment by thimmis** [comment]
I changed how 'condition' is initialized from a bool to None. I hope it works now. My intention was to have a general way of constructing the finite difference matrix and since I am only using Neumann BCs at left and right interfaces I needed something more to delineate how to construct the stamp describing this. In each room I create an object of behaviour_matrix that takes in the x, and y dimensions as well as a string 'r', 'l', 'rl', 'lr' that depending on the presence of specific characters gives the correct BCs.

**Comment by thimmis** [comment]
> I get the following error:
> 
> ```
In order for the multiprocessing to work you should have MPI4py installed. The code is executed as such:

$mpirun -n 5 python3 problem_solver.py

Where you specify the number of processes you want to use as well as the interpreter.
> $ python problem_solver.py 
> Traceback (most recent call last):
>   File "problem_solver.py", line 178, in <module>
>     tester(20,10)
>   File "problem_solver.py", line 170, in __call__
>     self.OM1, self.OM2, self.OM3, self.OM4 = self.dirichelt_neumann_iteration(self.heater, self.aircon, self.wall, cols, iters, open)
>   File "problem_solver.py", line 43, in dirichelt_neumann_iteration
>     livingroom = room_livingroom.LivingRoom(heater, aircon, walls, cols, open)
>   File "/Users/simonrose/Documents/coding/python/heat_equation/room_livingroom.py", line 91, in __init__
>     self.behaviour_matrix = matrix_creator.FiniteDiffMatrix(self.rows+2,self.cols+2).A
>   File "/Users/simonrose/Documents/coding/python/heat_equation/matrix_creator.py", line 37, in __init__
>     self.stamp = self.create_kron_stamp()
>   File "/Users/simonrose/Documents/coding/python/heat_equation/matrix_creator.py", line 69, in create_kron_stamp
>     if 'l' in self.condition:
> TypeError: argument of type 'bool' is not iterable
> ```
> 
> This seems to be because FiniteDiffMatrix has its condition initialized as a boolean, but it seems to serve a different purpose in create_kron_stamp(). However, this condition isn't ever passed as an argument in any of the places that call it.
